name: Build Linux And Debian
on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - 'Makefile'
      - '**.yml'
      - '*.yml'
jobs:
  build_linux_and_debian:
    name: Build Linux And Debian Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make Linux And Debian
      run: |
        rootpath="$(realpath .)"
        cd $rootpath
        if [[ -x "prebuild" ]]; then
          ./prebuild || exit 126
        else
          exit 127
        fi
        make releasedynamic || exit 125
        cppproj_linux_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "2E9778",\n\t"label": "cppproj MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "linux"\n}'
        if ! [[ -d "${rootpath}/docs/json" ]]; then
          mkdir -p .${rootpath}/docs/json || exit 124
        fi
        if ! [[ -f "${rootpath}/docs/json/cppproj_linux_md5.json" ]]; then
          touch "${rootpath}/docs/json/cppproj_linux_md5.json" || exit 123
        fi
        echo -e "$cppproj_linux_md5_text" > "${rootpath}/docs/json/cppproj_linux_md5.json" || exit 122
        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum ${rootpath}/release/dynamic/cppproj | cut -d' ' -f 1)\"/g" "${rootpath}/docs/json/cppproj_linux_md5.json" || exit 121
        cd ${rootpath}/debian || exit 120
        if [[ ! -d "${rootpath}/debian/cppproj-1.0.0/usr/bin" ]]; then
          mkdir -p "${rootpath}/debian/cppproj-1.0.0/usr/bin" || exit 119
        fi
        cp \
          "${rootpath}/release/dynamic/cppproj" \
          "${rootpath}/debian/cppproj-1.0.0/usr/bin/cppproj" || exit 118
        dpkg-deb --build --root-owner-group cppproj-1.0.0 || exit 117
        cppproj_debian_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "2E9778",\n\t"label": "cppproj-1.0.0.0.deb MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "debian"\n}'
        if ! [[ -f "${rootpath}/docs/json/cppproj_debian_md5.json" ]]; then
          touch "${rootpath}/docs/json/cppproj_debian_md5.json" || exit 116
        fi
        echo -e "$cppproj_debian_md5_text" > "${rootpath}/docs/json/cppproj_debian_md5.json" || exit 115
        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum ${rootpath}/debian/cppproj-1.0.0.deb | cut -d' ' -f 1)\"/g" "${rootpath}/docs/json/cppproj_debian_md5.json" || exit 114
        cd "${rootpath}"
        git add ${rootpath}/docs/json/* || exit 113
        git config --global user.name 'Lateralus138' || exit 112
        git config --global user.email 'Lateralus138@users.noreply.github.com' || exit 111
        git commit --allow-empty -am "Pushed $(printf '%s ' ${rootpath}/docs/json/*) to master. - $(date -u)" || exit 110
        git push --force origin master || exit 109
        echo -e "=========================\n========================="
        echo -e "=========================\n========================="
        echo "Planned failure - [255]"
        exit 255
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: 1.0.0
        name: Stable Release
        bodyFile: ./docs/md/pre-release.md
        prerelease: True
        artifacts: ./linux/release/dynamic/lspids,./debian/lspids-1.0.0.deb,./linux/android/static/32/lspids.arm32,./linux/android/static/64/lspids.aarch64
        token: ${{ secrets.GITHUB_TOKEN }}
